name: Arduino compile

on:
  push:
    branches:
      - 'master'

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Arduino compile job

    strategy:
      matrix:
        arduino-platform: ["esp32:esp32", "esp8266:esp8266"]
        include:
          - arduino-platform: "esp32:esp32"
            fqbn: "esp32:esp32:esp32"
            additional-urls: "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
          - arduino-platform: "esp8266:esp8266"
            fqbn: "esp8266:esp8266:generic"
            additional-urls: "https://arduino.esp8266.com/stable/package_esp8266com_index.json"

    steps:
      - uses: actions/checkout@v2
      - name: Setup arduino cli
        uses: arduino/setup-arduino-cli@v1
      - name: Install core
        run: |
          arduino-cli core update-index --additional-urls ${{ matrix.additional-urls }}
          arduino-cli core install ${{ matrix.arduino-platform }} --additional-urls ${{ matrix.additional-urls }}
      - name: Create arduino libraries folder
        run: mkdir -p ~/Arduino/libraries
      - name: Checkout espcd-library
        uses: actions/checkout@v2
        with:
          repository: espcd/espcd-library
          path: Arduino/libraries/espcd-library
      - run: ls ~/Arduino/libraries
      - run: ls ~/Arduino/libraries/espcd-library
      - name: Compile sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} espcd-example.ino
