name: Arduino compile

on:
  push:
    branches:
      - 'master'

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Arduino compile job

    strategy:
      matrix:
        fqbn: ["esp32:esp32:esp32", "esp8266:esp8266:generic"]
        include:
          - fqbn: "esp32:esp32:esp32"
            product: "8ab5ec33-a659-438e-a6ca-3db62b2141f0"
          - fqbn: "esp8266:esp8266:generic"
            product: "a56854b9-d4a3-412c-8966-aa2ca598ec5b"

    steps:
      - uses: actions/checkout@v2
      - name: Setup arduino cli
        uses: arduino/setup-arduino-cli@v1
      - uses: espcd/espcd-action@master
        with:
          fqbn: ${{ matrix.fqbn }}
          product: ${{ matrix.product }}
          sketch: ./espcd-example.ino
          title: 'test title'
          description: 'test description'
